import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Challenges from "@/components/Challenges";
import { useState } from "react";

export const accountId = "clifdp34m0000glmyquag4crh";

const Home: NextPage = () => {
  const [isCreateActive, setIsCreateActive] = useState(false);

  return (
    <>
      <Head>
        <title>Fitness Challenges</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full flex-col items-center p-2">
        <div>
          <button
            className={
              !isCreateActive
                ? "rounded-md bg-purple-600 p-2 text-white"
                : "rounded-md bg-red-600 p-2 text-white"
            }
            onClick={() => setIsCreateActive(!isCreateActive)}
          >
            {!isCreateActive ? "Create" : "Cancel"}
          </button>
        </div>
        <Challenges />
      </main>
    </>
  );
};

export default Home;
