import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Challenges from "@/components/Challenges";
import { useState } from "react";
import { DialogBox } from "@/components/DialogBox";
import { Button } from "@/components/ui/Button";
import { ThemeProvider } from "@/components/ui/ThemeProvider";
import NavBar from "@/components/NavBar";

export const accountId = "clifdp34m0000glmyquag4crh";

const Home: NextPage = () => {
  const [isCreateActive, setIsCreateActive] = useState(false);

  return (
    <>
      <Head>
        <title>Fitness Challenges</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <NavBar />
        <main className="flex w-full flex-col items-center p-2">
          <div>
            <DialogBox text="Create" />
            <Button variant="outline">Button</Button>
          </div>
          <Challenges />
        </main>
      </ThemeProvider>
    </>
  );
};

export default Home;
